apiVersion: v1
kind: ReplicationController
metadata:
  name: ${artifactId}
  namespace: ${kube-namespace}
spec:
  replicas: ${service-replicas}
  selector:
    app: ${artifactId}
  template:
    metadata:
      labels:
        app: ${artifactId}
    spec:
      serviceAccount: ${service-account}
      containers:
      - name: ${artifactId}
        image: ${docker-registry}/${docker-namespace}/${artifactId}:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080